checkbook/urls.py
from django.urls import path
from .views import CheckCreate, CheckDelete, CheckUpdate, CategoryCreate, CategoryDelete, CategoryUpdate
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('checkbookList', views.checkbookList, name='checkbook'),
    path('checks/', views.CheckListView.as_view(), name='check-list'),
    path('check/add/', views.CheckCreate.as_view(), name='check-add'),
    path('check/<int:pk>/', views.CheckUpdate.as_view(), name='check-detail'),
    path('check/<int:pk>/delete/', CheckDelete.as_view(), name='check-delete'),
    #path('check_form/', views.CheckCreate.as_view(), name='addcheck'),
    #path('check_update_form/<int:pk>', views.CheckUpdate.as_view(), name='updcheck'),
    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    #path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category/add/', views.CategoryCreate.as_view(), name='category-add'),
    path('category/<int:pk>/', views.CategoryUpdate.as_view(), name='category-detail'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category-delete'),

]

fmlcalendar/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.conf.urls import include
from django.urls import path

urlpatterns += [
    path('checkbook/', include('checkbook.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/checkbook/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

checkbook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Check(models.Model):

    """
    Model representing a checkbook transaction.
    """
    check_type = (
        ('CR', 'credit'),
        ('DR', 'debit'),
    )
    #theuser = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField(help_text=' .the date of the transaction')
    type = models.CharField(max_length=2, choices=check_type, help_text=' .credit or debit')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because a transaction can only have one category,
    # but categories can have multiple transactions
    # category as a string rather than object because it hasn't been
    # declared yet in the file.
    name = models.CharField(max_length=100, help_text=' .description')
    amount = models.IntegerField(default=0, help_text=' .amount')
    cleared = models.BooleanField(default=False, help_text=' .cleared with the bank?')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

    def short_description(self):
        return self.name[:25]

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this transaction.
        """
        return reverse('check-detail', kwargs={'pk': self.pk})

class Category(models.Model):

    """
    Model representing a Category.
    """
    name = models.CharField(max_length=100, help_text='Enter a category name')
    frequency = models.CharField(max_length=10, null=True, blank=True, help_text='Enter M(monthly) or W(weekly)')
    budget = models.IntegerField(default=0, help_text='Enter budgeted amount by frequency' )

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular category instance.
        """
        #return reverse('category-detail', args=[str(self.id)])
        return reverse('category-detail', kwargs={'pk': self.pk})

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}'.format(self.name)

checkbook/forms.py
from django import forms
from .models import Check, Category
#from django.core.exceptions import ValidationError
#from django.utils.translation import ugettext_lazy as _
#import datetime #for checking renewal date range.

class AddCheckForm(forms.Form):

    """
    Add checkbook transaction.
    """
    check_type = (
        ('CR', 'credit'),
        ('DR', 'debit'),
    )
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}),
        help_text='Enter the date of the transaction')
    type = forms.ChoiceField(choices=check_type, help_text='Enter credit or debit')
    category= forms.ModelChoiceField(queryset = Category.objects.all() )
    #a_category = forms.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    name = forms.CharField(help_text='Enter description')
    amount = forms.IntegerField(help_text='Enter amount')
    cleared = forms.BooleanField(help_text='Is transaction cleared with the bank?')

    #renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    # def clean_renewal_date(self):
    #     data = self.cleaned_data['renewal_date']
    #
    #     #Check date is not in past.
    #     if data < datetime.date.today():
    #         raise ValidationError(_('Invalid date - renewal in past'))
    #
    #     #Check date is in range librarian allowed to change (+4 weeks).
    #     if data > datetime.date.today() + datetime.timedelta(weeks=4):
    #         raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
    #
    #     # Remember to always return the cleaned data.
    #     return data

checkbook/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django import forms
from datetime import date
from .models import Check, Category

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_checks=Check.objects.all().count()
    tot_bal=Check.objects.all().aggregate(Sum('amount'))
    today_bal=Check.objects.filter(date__lte=date.today()).aggregate(Sum('amount'))
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_checks':num_checks,'tot_bal':tot_bal, 'today_bal':today_bal,
            'num_visits':num_visits},
    )

def checkbookList(request):
    checks = Check.objects.all()
    balance = 0
    for chk in checks:
        balance += chk.amount
        chk.balance = balance

    return render(request, 'checkbook.html', {'checks': checks})


from django.views import generic

class CheckListView(generic.ListView):
    model = Check
    paginate_by = 10

class CheckDetailView(generic.DetailView):
    model = Check

class CheckForm(forms.ModelForm):
    class Meta:
        model = Check
        fields = ['date', 'type', 'category', 'name', 'amount', 'cleared']
        widgets = {
            'date': forms.TextInput(attrs={'class':'datepicker'})
        }

class CheckCreate(CreateView):
    form_class = CheckForm
    model = Check
    success_url = reverse_lazy('check-list')

class CheckUpdate(UpdateView):
    model = Check
    success_url = reverse_lazy('check-list')
    fields = ['date', 'type', 'category', 'name', 'amount', 'cleared']
    #template_name_suffix = '_update_form'

class CheckDelete(DeleteView):
    model = Check
    success_url = reverse_lazy('check-list')

# Category views
# --------------------------------------------
class CategoryListView(generic.ListView):
    model = Category
    paginate_by = 10

class CategoryDetailView(generic.DetailView):
    model = Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'frequency', 'budget']

class CategoryCreate(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('category-list')



class CategoryUpdate(UpdateView):
    model = Category
    success_url = reverse_lazy('category-list')
    fields = ['name', 'frequency', 'budget']
    #template_name_suffix = '_update_form'

class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('category-list')

checkbook/templates/checkbook/category_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>.fml finanace .delete category</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

checkbook/templates/checkbook/category_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>. category: {{ category.name }}</h1>

  <p><strong>category:</strong> {{ category.name }}</p>
  <p><strong>budget frequency:</strong> {{ category.frequency }}</p>
  <p><strong>budget amount:</strong> {{ category.budget }}</p>
  
{% endblock %}

checkbook/templates/checkbook/category_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .add category</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>

{% endblock %}

checkbook/templates/checkbook/category_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h2>.fml finance .categories</h2>

    <a href="{% url 'category-add' %}">add new</a>

    {% if category_list %}
    <ul>

      {% for category in category_list %}
      <li>
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a> ({{ category.budget }} : {{category.frequency}})...
          <a href="{% url 'category-delete' category.id %}">delete</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no catgories, get your shit together.</p>
    {% endif %}
{% endblock %}

checkbook/templates/checkbook/category_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .update category</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>

{% endblock %}

checkbook/templates/checkbook/check_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>.fml finanace .checkbook</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

checkbook/templates/checkbook/check_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ check.name }}</h1>

  <p><strong>date:</strong> {{ check.date }}</p>
  <p><strong>name:</strong> {{ check.name }}</p>
  <p><strong>type:</strong> {{ check.type }}</p>
  <p><strong>category:</strong> <a href="{% url 'category-detail' check.category.pk %}">{{ check.category }}</a></p>
  <p><strong>amount:</strong> {{ check.amount }}</p>
  <p><strong>is cleared:</strong> {{ check.cleared }}</p>

{% endblock %}

<a href="{% url 'check-update' %}">update transaction</a>

checkbook/templates/checkbook/check_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .add transaction</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>

{% endblock %}

<script>
  $(function() {
      $( "#id_date" ).datepicker();
  });
</script>

checkbook/templates/checkbook/check_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h2>.fml finanace .checkbook</h2>

    <a href="{% url 'check-add' %}">add new</a>

    {% if check_list %}
    <ul>

      {% for check in check_list %}
      <li>
        {{ check.date|date:'Y M d' }}:
        <a href="{{ check.get_absolute_url }}"> {{ check.name }}</a> ({{check.amount}})
        <a href="{% url 'check-delete' check.id %}">delete</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no checks in the checkbook.</p>
    {% endif %}

{% endblock %}

checkbook/templates/checkbook/check_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .update transaction</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>

{% endblock %}

<script>
  $(function() {
      $( "#id_date" ).datepicker();
  });
</script>